name: "GitHub Repository Insights"
description: "Preserve GitHub insights beyond 14 days with a built-in GitHub Pages dashboard"
branding:
  icon: "bar-chart"
  color: "orange"

inputs:
  pat-token:
    description: "GitHub Personal Access Token for fetching repository data"
    required: true
  repos:
    description: "Comma-separated list of repositories (e.g., owner/repo,owner/repo2)."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.pat-token }}
    - ${{ inputs.repos }}
